const BREVO_API_KEY = process.env.BREVO_API_KEY;
const FROM_EMAIL = process.env.BREVO_FROM_EMAIL ?? "alerts@guardianlayer.app";
const FROM_NAME = "Guardian Layer";

type EmailParams = {
  to: string;
  subject: string;
  html: string;
};

export async function sendEmail({ to, subject, html }: EmailParams): Promise<boolean> {
  if (!BREVO_API_KEY) {
    console.warn("[email] BREVO_API_KEY not set, skipping");
    return false;
  }

  try {
    const res = await fetch("https://api.brevo.com/v3/smtp/email", {
      method: "POST",
      headers: {
        "api-key": BREVO_API_KEY,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({
        sender: { name: FROM_NAME, email: FROM_EMAIL },
        to: [{ email: to }],
        subject,
        htmlContent: html,
      }),
    });

    if (!res.ok) {
      const err = await res.text();
      console.error("[email] Brevo error:", res.status, err);
      return false;
    }

    return true;
  } catch (err) {
    console.error("[email] Send failed:", err);
    return false;
  }
}

export function buildCriticalVerdictEmail(params: {
  orgName: string;
  protocolName: string;
  incidentTitle: string;
  threatLevel: string;
  recommendedAction: string;
  reasoning: string;
  incidentUrl: string;
  autoPaused: boolean;
}): { subject: string; html: string } {
  const { orgName, protocolName, incidentTitle, threatLevel, recommendedAction, reasoning, incidentUrl, autoPaused } = params;

  const subject = `🚨 ${threatLevel.toUpperCase()} verdict on ${protocolName} — ${incidentTitle}`;

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#070A12;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:32px 24px;">
    <div style="margin-bottom:24px;">
      <span style="color:#38BDF8;font-size:14px;font-weight:700;letter-spacing:2px;">GUARDIAN LAYER</span>
    </div>

    <div style="background:#0D111C;border:1px solid ${threatLevel === 'critical' ? '#EF4444' : '#F97316'};border-radius:12px;padding:24px;margin-bottom:24px;">
      <div style="display:inline-block;background:${threatLevel === 'critical' ? '#450a0a' : '#451a03'};color:${threatLevel === 'critical' ? '#EF4444' : '#F97316'};padding:4px 12px;border-radius:6px;font-size:12px;font-weight:700;margin-bottom:12px;">
        ${threatLevel.toUpperCase()}
      </div>
      <h2 style="color:#F4F7FB;font-size:18px;margin:8px 0 4px;">${incidentTitle}</h2>
      <p style="color:#9AA7B8;font-size:13px;margin:0 0 16px;">Protocol: ${protocolName} · Organisation: ${orgName}</p>

      <div style="background:#070A12;border:1px solid #243044;border-radius:8px;padding:16px;margin-bottom:16px;">
        <p style="color:#64748B;font-size:11px;text-transform:uppercase;letter-spacing:1px;margin:0 0 8px;">AI Verdict Reasoning</p>
        <p style="color:#F4F7FB;font-size:13px;margin:0;line-height:1.5;">${reasoning || 'No reasoning provided.'}</p>
      </div>

      <table style="width:100%;font-size:12px;color:#9AA7B8;">
        <tr>
          <td style="padding:4px 0;">Recommended Action</td>
          <td style="padding:4px 0;text-align:right;color:#F4F7FB;font-weight:600;">${recommendedAction}</td>
        </tr>
        <tr>
          <td style="padding:4px 0;">Auto-Pause Triggered</td>
          <td style="padding:4px 0;text-align:right;color:${autoPaused ? '#EF4444' : '#22C55E'};font-weight:600;">${autoPaused ? 'YES' : 'No'}</td>
        </tr>
      </table>
    </div>

    <a href="${incidentUrl}" style="display:inline-block;background:#38BDF8;color:#070A12;padding:10px 24px;border-radius:8px;font-size:13px;font-weight:700;text-decoration:none;">
      View Incident →
    </a>

    <p style="color:#64748B;font-size:11px;margin-top:32px;border-top:1px solid #243044;padding-top:16px;">
      This alert was generated by Guardian Layer's GenLayer AI consensus engine. GenLayer is the authoritative source of truth for emergency threat judgement.
    </p>
  </div>
</body>
</html>`;

  return { subject, html };
}
